ktor:
  development: true
  application:
    modules:
      - kr.donghune.calendar.ApplicationKt.module
  deployment:
    port: 8081
    host: 0.0.0.0

postgres:
  url: "jdbc:postgresql://postgres:5432/mogako_calendar"
  user: "mogako"
  password: "mogako123"