ktor:
  development: true
  application:
    modules:
      - kr.donghune.auth.ApplicationKt.module
  deployment:
    port: 8080
    host: 0.0.0.0

postgres:
  url: "jdbc:postgresql://postgres:5432/mogako_auth"
  user: "mogako"
  password: "mogako123"