name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'build:')

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Extract project version
      id: project_version
      run: |
        VERSION=$(grep -m 1 "version = " build.gradle.kts | sed 's/.*version = "\(.*\)".*/\1/')
        echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV
        echo "Extracted version: $VERSION"

    - name: Run tests
      run: ./gradlew test

    - name: Build Docker images
      run: |
        ./gradlew :auth-api:buildImage
        ./gradlew :calendar-api:buildImage
      env:
        API_VERSION: ${{ env.PROJECT_VERSION }}.${{ github.run_number }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Publish Docker images
      run: |
        ./gradlew :auth-api:publishImage
        ./gradlew :calendar-api:publishImage
      env:
        API_VERSION: ${{ env.PROJECT_VERSION }}.${{ github.run_number }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
